# Generated by Django 4.1.7 on 2023-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
