# Generated by Django 4.1.7 on 2023-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'Активна'), ('False', 'Неактивна')], default='False', max_length=10, verbose_name='Признак публикации'),
        ),
    ]
